<?PHP if ($_SESSION["tusu"] == 1){
       echo "<div class=tabMenu>";
	 	 echo "<div class=Estilo1>Administrador del Sistema</div>";
		 echo  "<div class=titulo><a href='crearusuario.php'>Crear Usuarios</a></div>";
         echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
	 	 echo "<div class=Estilo1>Comercializaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='empresa.php'>Comercializar</a></div>";
		 echo  "<div class=titulo><a href='conscontra.php'>Consultar Contrato</a></div>";
	   	 echo "<div class=titulo><a href='regisstan.php'>Crear Stand</a></div>";
		 echo "<div class=titulo><a href='costostan.php'>Modificar Stand</a></div>";
         echo "<div class=titulo><a href='crearubi.php'>Crear Ubicaci&oacute;n</a></div>";
	     echo "<div class=titulo><a href='modifubi.php'>Modificar Ubicaci&oacute;n</a></div>"; 	 
		 echo "<div  class=Estilo1>Reportes Comercializaci&oacute;n</div>";
		 echo "<div class=titulo><a href='porfecha.php'>Ventas por Fecha</a></div>";
		 echo "<div class=titulo><a href='pordispo.php'>Disponibilidad por Ubicaci&oacute;n</a></div>";
 		 echo "<div class=titulo><a href='porbaucher.php'>Depositos Recibidos</a></div>";
 	 	 echo "<div class=titulo><a href='porempresa.php'>Empresas Deudoras</a></div>";
		 echo "<div class=titulo><a href='reportusucomer.php'>Contratos por Usuario</a></div>";
		 echo "<div class=titulo><a href='reportespacios.php'>Espacios Comercializados</a></div>";
		 echo "<div class=titulo><a href='listadostand.php'>Listado de Stand</a></div>";
		 echo  "<div class=Estilo1>Acreditaci&oacute;n</div>";
 		 echo  "<div class=titulo><a href='registroentes.php'>Registrar Comisiones</a></div>";
		 //echo  "<div class=titulo><a href='acremp.php'>Registrar Acreditados</a></div>";
		  echo  "<div class=titulo><a href='empresa2.php'>Registrar Acreditados</a></div>";
		 echo "<div class=titulo><a href='consultacre2.php'>Consultar Acreditados</a></div>";
	     echo  "<div class=titulo><a href='buscaacr.php'>Modificar Acreditados</a></div>";	
		 echo "<div  class=Estilo1>Reportes Acreditaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='reporentes.php'>Reporte Comisiones</a></div>";
		 echo  "<div class=titulo><a href='reporempre.php'>Reporte Empresas</a></div>";
		 echo  "<div class=titulo><a href='reportacre.php'>Reporte Acreditaciones</a></div>";
		 echo  "<div class=titulo><a href='reportusuacred.php'>Acreditaciones por Usuario</a></div>";
		 echo "<div class=titulo><a href='consultacre.php'>Acreditaci&oacute;n</a></div>";
		 echo  "<div class=Estilo1>Abonos</div>";
		// echo  "<div class=titulo><a href='ventaabono.php'>Realizar Venta</a></div>";
		 echo  "<div class=titulo><a href='codigoabono.php'>Crear Abonos</a></div>";
 	     echo  "<div class=titulo><a href='conimpAbo.php'>Imprimir Abonos</a></div>";	
		// echo "<div  class=Estilo1>Reportes Abonos</div>";
		// echo "<div class=titulo><a href='abonofecha.php'>Ventas por Fecha</a></div>";
		 echo "<div  class=Estilo1>&nbsp;</div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";		 		 
	  echo "</div>";
         }elseif ($_SESSION["tusu"] == 6){
	  echo "<div class=tabMenu>";
	 	 echo "<div class=Estilo1>Administrador Comercializaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='empresa.php'>Comercializar</a></div>";
		 echo  "<div class=titulo><a href='conscontra.php'>Consultar Contrato</a></div>";
	   	 echo "<div class=titulo><a href='regisstan.php'>Crear Stand</a></div>";
		 echo "<div class=titulo><a href='costostan.php'>Modificar Stand</a></div>";
         echo "<div class=titulo><a href='crearubi.php'>Crear Ubicaci&oacute;n</a></div>";
	     echo "<div class=titulo><a href='modifubi.php'>Modificar Ubicaci&oacute;n</a></div>"; 
		 //echo  "<div class=titulo><a href='crearusuario.php'>Crear Usuarios</a></div>";
         echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
		 echo "<div  class=Estilo1>Reportes</div>";
		 echo "<div class=titulo><a href='porfecha.php'>Ventas por Fecha</a></div>";
		 echo "<div class=titulo><a href='pordispo.php'>Disponibilidad por Ubicaci&oacute;n</a></div>";
 		 echo "<div class=titulo><a href='porbaucher.php'>Depositos Recibidos</a></div>";
		 echo "<div class=titulo><a href='reportespacios.php'>Espacios Comercializados</a></div>";
 	 	 echo "<div class=titulo><a href='porempresa.php'>Empresas Deudoras</a></div>";
		 echo "<div class=titulo><a href='reportusucomer.php'>Contratos por Usuario</a></div>";
		 echo "<div class=titulo><a href='listadostand.php'>Listado de Stand</a></div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
	  echo "</div>";		 
		 }elseif ($_SESSION["tusu"] == 7){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Comercializaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='empresa.php'>Comercializar</a></div>";
		 echo  "<div class=titulo><a href='conscontra.php'>Consultar Contrato</a></div>";
		 echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
		 echo "<div  class=Estilo1>Reportes</div>";
		 echo "<div class=titulo><a href='porfecha.php'>Ventas por Fecha</a></div>";
		 echo "<div class=titulo><a href='pordispo.php'>Disponibilidad por Ubicaci&oacute;n</a></div>";
 		 echo "<div class=titulo><a href='porbaucher.php'>Depositos Recibidos</a></div>";
 	 	 echo "<div class=titulo><a href='porempresa.php'>Empresas Deudoras</a></div>";
 		 echo "<div class=titulo><a href='listadostand.php'>Listado de Stand</a></div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
     echo "</div>";
	     }elseif ($_SESSION["tusu"] == 5){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Venta Abonos</div>";
	//	 echo  "<div class=titulo><a href='ventaabono.php'>Realizar Venta</a></div>";
	//	 echo "<div  class=Estilo1>Reportes</div>";
	//	 echo "<div class=titulo><a href='abonofecha.php'>Ventas por Fecha</a></div>";
	    echo "</div>";
		}elseif ($_SESSION["tusu"] == 4){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Administrador Abonos</div>";
		 echo  "<div class=titulo><a href='codigoabono.php'>Crear Abonos</a></div>";
 	     echo  "<div class=titulo><a href='conimpAbo.php'>Imprimir Abonos</a></div>";	
	     echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
		// echo "<div  class=Estilo1>Reportes</div>";
		// echo "<div class=titulo><a href='abonofecha.php'>Ventas por Fecha</a></div>";
	    echo "</div>";
         }
		elseif ($_SESSION["tusu"] == 10){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Empresa</div>";
		 echo  "<div class=titulo><a href='acremp.php'>Registrar Acreditados</a></div>";
		 echo "<div  class=Estilo1>Reportes</div>";
		 echo "<div class=titulo><a href='consultacre.php'>Acreditaci&oacute;n</a></div>";
		 echo "<div  class=Estilo1>&nbsp;</div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
	    echo "</div>";
         }elseif ($_SESSION["tusu"] == 8){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Avanzado Acreditaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='registroentes.php'>Registrar Comisiones</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Registrar Acreditado</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Consultar Acreditado</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Imprimir Acreditaci&oacute;n</a></div>";
		 echo "<div  class=Estilo1>Reportes</div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte Comisiones</a></div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte Acreditaciones</a></div>";
		 echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
	    echo "</div>";
         }elseif ($_SESSION["tusu"] == 2){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Administrador Acreditaci&oacute;n</div>";
		 echo  "<div class=titulo><a href='registroentes.php'>Registrar Comisiones</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Registrar Acreditado</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Consultar Acreditado</a></div>";
	    // echo  "<div class=titulo><a href='registroentes.php'>Eliminar Acreditaci&oacute;n</a></div>";
	    // echo  "<div class=titulo><a href='registroentes.php'>Liberar Acreditaci&oacute;n</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Imprimir Acreditaci&oacute;n</a></div>";
	     echo "<div  class=Estilo1>Reportes</div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte Comisiones</a></div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte Acreditaciones</a></div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte de Usuario</a></div>";
		 echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
	    echo "</div>";
         }elseif ($_SESSION["tusu"] == 3){
       echo "<div class=tabMenu>";
		 echo  "<div class=Estilo1>Usuario Acreditador</div>";
		 echo  "<div class=titulo><a href='registroentes.php'>Registrar Comisiones</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Registrar Acreditado</a></div>";
		// echo  "<div class=titulo><a href='registroentes.php'>Consultar Acreditado</a></div>";
		 echo "<div  class=Estilo1>Reportes</div>";
		// echo  "<div class=titulo><a href='cambiarclave.php'>Reporte de Usuario</a></div>";
		 echo  "<div class=titulo><a href='cambiarclave.php'>Cambiar Clave</a></div>";
		 echo "<div class=titulo><a href=cerrar.php>Cerrar Sesi&oacute;n</a></div>";
	    echo "</div>";
         }	 	 
   ?>